### ISSUE TITLE
[Feature suggestion] Print concise error message on network errors, not some "cryptic" rust panics.

### ISSUE THREAD

**Issue by dreirund** [hgrahamcs/amimullvad#2]
Ahoj,

when there is no internet connection, `amimullvad` prints a needlessly complex rust error message.

I hereby feature-suggest to instead print precisely the error (like "*Could not resolve host: am.i.mullvad.net*", and exit with the approprieate exitcode of e.g. `curl` if you use that).

Current behaviour:

```
thread 'main' panicked at src/main.rs:13:16:
called `Result::unwrap()` on an `Err` value: Error { description: "Could not resolve hostname", code: 6, extra: Some("Could not resolve host: am.i.mullvad.net") }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

It even sugests to run with `RUST_BACKTRACE` set (which is needless here). But if I do  
`RUST_BACKTRACE=1 amimullvad`:  
```
thread 'main' panicked at src/main.rs:13:16:
called `Result::unwrap()` on an `Err` value: Error { description: "Could not resolve hostname", code: 6, extra: Some("Could not resolve host: am.i.mullvad.net") }
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

And if I then do the suggested `RUST_BACKTRACE=full amimullvad`:  
```
thread 'main' panicked at src/main.rs:13:16:
called `Result::unwrap()` on an `Err` value: Error { description: "Could not resolve hostname", code: 6, extra: Some("Could not resolve host: am.i.mullvad.net") }
stack backtrace:
   0:     0x560f2bf5b255 - <unknown>
   1:     0x560f2bf770ab - <unknown>
   2:     0x560f2bf595af - <unknown>
   3:     0x560f2bf5c3a1 - <unknown>
   4:     0x560f2bf5c07c - <unknown>
   5:     0x560f2bf5c971 - <unknown>
   6:     0x560f2bf5c867 - <unknown>
   7:     0x560f2bf5b719 - <unknown>
   8:     0x560f2bf5c4f4 - <unknown>
   9:     0x560f2bf37af3 - <unknown>
  10:     0x560f2bf37ee6 - <unknown>
  11:     0x560f2bf38d5b - <unknown>
  12:     0x560f2bf38323 - <unknown>
  13:     0x560f2bf38319 - <unknown>
  14:     0x560f2bf56e20 - <unknown>
  15:     0x560f2bf38e95 - <unknown>
  16:     0x7f60f26b4d6e - <unknown>
  17:     0x7f60f26b4e2a - __libc_start_main
  18:     0x560f2bf38235 - <unknown>
  19:                0x0 - <unknown>
```

Regards!

**Comment by hgrahamcs** [comment]
Same deal as in #1, I'm out of time for the morning but this is a reasonable ask and I'll fix it.
